### ISSUE TITLE
feat: 엔티티 수정 및 매핑

### ISSUE THREAD

**Issue by Jinwon-Dev** [Team-Code-200/santa-clothes-backend#23]
## Description
누락되고 필요한 엔티티를 추가하고, 관계를 매핑합니다.
연관관계 편의 메소드를 작성하고, 정적 생성자를 추가합니다.

</br>

## To-do
- [x] 엔티티 추가 및 관계 매핑
- [x] 연관관계 편의 메소드 작성
- [x] 정적 생성자 추가

</br>

## ETC
기타사항
