### ISSUE TITLE
feat: 산타샵 도메인 개발

### ISSUE THREAD

**Issue by Jinwon-Dev** [Team-Code-200/santa-clothes-backend#26]
## Description
산타샵(포인트 물품 샵) 도메인을 개발합니다.

</br>

## To-do
- [ ] 산타샵 물품 생성(관리자)
- [ ] 산타샵 물품 조회
- [ ] 산타샵 물품 수정(관리자)
- [ ] 산타샵 물품 삭제(관리자)

</br>

## ETC
기타사항
