### ISSUE TITLE
feat: 엔티티 제약조건 및 기본값 추가

### ISSUE THREAD

**Issue by Jinwon-Dev** [Team-Code-200/santa-clothes-backend#8]
## Description
엔티티에 not null, unique 제약조건을 추가합니다.
로직에서 검사를 하지만, 추가적으로 추가합니다.

</br>

## To-do
- [x] not null 제약조건 추가
- [x] unique 제약조건 추가
- [x] 조회수 기본값 추가

</br>

## ETC
- https://github.com/Team-Code-200/santa-clothes-backend/pull/9
